### PR TITLE
Kadane's Algo edit.

### PR DESCRIPTION
**Pull request by Dev-kabir-ai**

### CODE REVIEW

**Comment by Dev-kabir-ai** [comment]
Done, Please review and merge.

**Comment by Dev-kabir-ai** [comment]
you have merged my branch but in my hacktoberfest profile it is showing not accepted.

**Comment by Dipak3007** [comment]
Refresh hacktoberfest page 2 to 3 times

**Comment by Dev-kabir-ai** [comment]
it worked, thanks.

**Pull request merged**
